
dataset:
  data_name: "ihdp"

train:
  epochs: 3000
  batch_size: 512
  lr: 0.0001
  valid_epoch_interval: 200

diffusion:
  layers: 4
  channels: 64
  f_dim: 180
  cond_dim: 26 # conditional variable dimension # 177 + 1
  hidden_dim: 128
  side_dim: 33
  nheads: 2 #4
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 100
  schedule: "quad"
  mixed: False

model:
  is_unconditional: 0
  timeemb: 32
  featureemb: 32 #16
  target_strategy: "random"
  mixed: False
